### ISSUE TITLE
Action fails after recent change to entrypoint.sh

### ISSUE THREAD

**Issue by pmoccioTVR** [dmnemec/copy_file_to_another_repo_action#39]
I have a number of workflows that use this action and they're failing with this error after the recent change to entrypoint.sh:

```
Cloning into '/tmp/tmp.icEILo'...
+ echo 'Copying contents to git repo'
Copying contents to git repo
+ mkdir -p /tmp/tmp.icEILo/
+ rsync -avrh CHANGELIST.md /tmp/tmp.icEILo/
/entrypoint.sh: line 27: rsync: not found
```

**Comment by kickbutts** [comment]
The same with me
`/entrypoint.sh: line 27: rsync: not found`

**Comment by Jason2866** [comment]
I forked the repo and reverted the faulty change and use the fork. Works!

**Comment by eranelbaz** [comment]
We are also having this problem

**Comment by philipturner** [comment]
Same problem.

**Comment by Niek** [comment]
Same here

**Comment by dmnemec** [comment]
I fixed the rsync not found problem and made it an optional feature on Latest (setting the `use_rsync` var will enable it). Line 27 was the rsync line.
