### ISSUE TITLE
URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by SpyrexDE** [dmnemec/copy_file_to_another_repo_action#44]
I try to use this action for my GitHub organization.
So for `destination_repo`, I entered `'ORGANIZATION_NAME/REPO_NAME'`.
However, I then get the following error:
`fatal: unable to access 'https:///ORGANIZATION_NAME/REPO_NAME.git/': URL using bad/illegal format or missing URL`

**Comment by technorabilia** [comment]
Having the same issue.

Unfortunately, setting `github_server` or `git_server` to 'github.com' does not work for me.

**Comment by DominiqueMakowski** [comment]
I confirm having the same issue

**Comment by dmnemec** [comment]
@stetttho Yeah, sorry about that. Not sure how it passed my tests. I'll check tonight if it somehow worked and shouldn't have. I'm not on Github much since my work uses a private one so I'm a little slower to respond to these things.

**Comment by dmnemec** [comment]
Just realized the PR that caused it was merged from an outside repo so it didn't run checks on it until the merge *faceplam*
