### ISSUE TITLE
"commit_message" is missing

### ISSUE THREAD

**Issue by TomasVotruba** [dmnemec/copy_file_to_another_repo_action#7]
Hi,

thank you for this package. It might be exactly what I need for package splitting.

I have a trouble with missing "commit_message":

![image](https://user-images.githubusercontent.com/924196/97849898-86da0d80-1cf3-11eb-8d67-c6b86fdde959.png)

Do I have a typo or something?

**Comment by bboles** [comment]
#12 
I think my pull request should resolve this issue.

**Comment by bboles** [comment]
Hey @dmnemec, would it be possible to merge my pull request?

**Comment by dmnemec** [comment]
Closed by #12 , thanks. If you want to write a test for it to make sure it adds a message, that'd be cool too.
