### ISSUE TITLE
Includes multiple files in source_file

### ISSUE THREAD

**Issue by mostafasoufi** [dmnemec/copy_file_to_another_repo_action#80]
Hey!

Is it double to include more than one file in `source_file`? something like 

```
source_file: 'dist/assets/*
```
![_tqOflNX](https://github.com/dmnemec/copy_file_to_another_repo_action/assets/701520/d3fe41a2-c902-4836-a0e0-1c9ff4c9f573)

**Comment by dobbelina** [comment]
@mostafasoufi 
With this source_file it will copy everything in the assets folder recursively:
`source_file: 'dist/assets/'`
With this source_file it will copy everything in the assets folder recursively
but not hidden files or folders that starts with a "." in the file/folder name.
`source_file: 'dist/assets/*'`

If you want to copy multiple files from different source files/folders use [my fork](https://github.com/dobbelina/copy_file_to_another_repo_action)

**Comment by mostafasoufi** [comment]
Sounds great, thank you!

Btw, would be great to put this info into the readme.md
