### ISSUE TITLE
Error when building dmnemec/copy_file_to_another_repo_action@main

### ISSUE THREAD

**Issue by carsonstuart143** [dmnemec/copy_file_to_another_repo_action#87]
Running into the following error when trying to use workflow. Was working last week and I changed nothing on my end but it seems to have problems updating. If anyone has any solution to this problem please let me know.

  Dockerfile:3
  --------------------
     2 |     
     3 | >>> RUN apk update && \
     4 | >>>     apk upgrade && \
     5 | >>>     apk add git rsync
     6 |     
  --------------------
  ERROR: failed to solve: process "/bin/sh -c apk update &&     apk upgrade &&     apk add git rsync" did not complete successfully: exit code: 1

**Comment by abbyck** [comment]
This looks like an alpine upstream problem
https://gitlab.alpinelinux.org/alpine/apk-tools/-/issues/10990
```
docker run -it alpine /bin/sh
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/aarch64/APKINDEX.tar.gz
v3.19.1-320-gee4356e1e02 [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]
v3.19.1-319-gba207bb09fa [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]
OK: 22839 distinct packages available
/ # apk upgrade
Upgrading critical system libraries and apk-tools:
(1/1) Upgrading apk-tools (2.14.0-r5 -> 2.14.3-r0)
ERROR: apk-tools-2.14.3-r0: BAD signature
Continuing the upgrade transaction with new apk-tools:
(1/2) Upgrading ca-certificates-bundle (20230506-r0 -> 20240226-r0)
(2/2) Upgrading apk-tools (2.14.0-r5 -> 2.14.3-r0)
ERROR: apk-tools-2.14.3-r0: BAD signature
1 error; 8 MiB in 15 packages
```

**Comment by abbyck** [comment]
They seem to have fixed the repositories. Able to do apk upgrade now

**Comment by KenHuPricer** [comment]
> They seem to have fixed the repositories. Able to do apk upgrade now

+1

**Comment by carsonstuart143** [comment]
resolved
