### ISSUE TITLE
Make action work for github apps

### ISSUE THREAD

**Issue by drakos74** [dmnemec/copy_file_to_another_repo_action#9]
For github apps, the action fails due to the http API call for checkout `clone`.

```
+ git clone --single-branch --branch $INPUT_DESTINATION_BRANCH "https://$API_TOKEN_GITHUB@github.com/$INPUT_DESTINATION_REPO.git" /tmp/tmp.iCiMJM
Cloning into '/tmp/tmp.iCiMJM'...
fatal: could not read Password for 'https://***@github.com': No such device or address
```

According to this : https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation 
The http call needs to be adjusted.

This change will allow the action to be used both with `personal access token` and `temporary installation token` .
And will enable a broader range of users to make use of this action.

**Comment by brenoalvs** [comment]
I'm receiving this error in one of my repositories with a regular workflow.

**Comment by xelzi** [comment]
It would be nice to add some sort of note in the docs about the token that needs to be included in the workflow.

As somebody new to integrating with actions, I spent a good amount of time realizing that  `API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}` was not the same as the standard `GITHUB_TOKEN`

**Comment by dmnemec** [comment]
Sounds like a good thing to mention. I need to update docs with the commit message stuff, too, so I'll grab this then.

**Comment by DavidOry** [comment]
> It would be nice to add some sort of note in the docs about the token that needs to be included in the workflow.
> 
> As somebody new to integrating with actions, I spent a good amount of time realizing that `API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}` referenced a personal access token and that the standard `GITHUB_TOKEN` would not have sufficient permissions.

@xelzi I'm also new to actions and ran into the same problem as you. But need help with the next step. After setting up a personal access token, what do I need to do so that it is recognized by the `${{ secrets.API_TOKEN_GITHUB }}` reference? thanks in advance for the help.

**Comment by drakos74** [comment]
@DavidOry , if i understand your issue correctly , you need to reference your own token with something like this https://bloggie.io/@_junrong/using-environment-variables-secrets-in-github-actions#secrets . Hope that helps.

**Comment by xelzi** [comment]
> > It would be nice to add some sort of note in the docs about the token that needs to be included in the workflow.
> > As somebody new to integrating with actions, I spent a good amount of time realizing that `API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}` referenced a personal access token and that the standard `GITHUB_TOKEN` would not have sufficient permissions.
> 
> @xelzi I'm also new to actions and ran into the same problem as you. But need help with the next step. After setting up a personal access token, what do I need to do so that it is recognized by the `${{ secrets.API_TOKEN_GITHUB }}` reference? thanks in advance for the help.

If the repositories you are copying files between are under the same organization you can add an org secret: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization

Otherwise, you need to make sure both repos have access to the secret a la: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-environment

Hope that helps!
